# Generated by Django 2.0.13 on 2019-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
