# Generated by Django 2.0.13 on 2019-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
