# Generated by Django 2.0.13 on 2019-07-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190702_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsription',
            new_name='Subscription',
        ),
    ]
