# Generated by Django 2.0.13 on 2019-07-06 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190702_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=256, verbose_name='Title')),
                ('event_location', models.CharField(max_length=200, verbose_name='Location')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('event_description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Addresse '),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name (optional) '),
        ),
    ]
